# Generated by Django 3.1.1 on 2021-01-08 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('field', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('paperAbstract', models.TextField()),
                ('year', models.IntegerField()),
                ('s2Url', models.URLField()),
                ('doiUrl', models.URLField(null=True)),
                ('authors', models.ManyToManyField(to='graphgenerator.Author')),
                ('fieldsOfStudy', models.ManyToManyField(to='graphgenerator.FieldOfStudy')),
                ('inCitations', models.ManyToManyField(related_name='_paper_inCitations_+', to='graphgenerator.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='PdfUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphgenerator.paper')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphgenerator.author')),
            ],
        ),
    ]
