# Generated by Django 3.1.1 on 2021-01-13 23:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', 'trigrammigration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='graph_paper_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
