# Generated by Django 3.1.1 on 2021-01-13 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0001_auto_20210113_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdfUrl',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
