# Generated by Django 3.1.1 on 2021-01-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paperAbstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='s2Url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
