# Generated by Django 3.1.1 on 2021-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0002_auto_20210109_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='s2Url',
            field=models.URLField(default='localhost'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuthorID',
        ),
    ]
