# Generated by Django 3.1.1 on 2021-01-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0003_delete_pdfurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citations',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
