# Generated by Django 3.1.1 on 2021-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0004_auto_20210110_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
