# Generated by Django 3.1.1 on 2021-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0004_paper_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
