# Generated by Django 3.1.2 on 2021-02-12 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0005_paper_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='pdfUrl',
            new_name='pdfUrls',
        ),
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='journalName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='journalPages',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='paper',
            name='journalVolume',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paper',
            name='magId',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paper',
            name='venue',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='fieldsOfStudy',
        ),
        migrations.AddField(
            model_name='paper',
            name='fieldsOfStudy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
