# Generated by Django 3.1.1 on 2021-01-10 16:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0005_auto_20210110_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='graphgenera_search__7a75a9_gin'),
        ),
    ]
