# Generated by Django 3.1.2 on 2021-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0006_auto_20210212_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journalName',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journalPages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journalVolume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='magId',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='venue',
            field=models.TextField(blank=True),
        ),
    ]
