# Generated by Django 3.1.5 on 2021-02-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0008_auto_20210216_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpaper',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='graphgenerator.author'),
        ),
        migrations.AlterField(
            model_name='authorpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='graphgenerator.paper'),
        ),
    ]
