# Generated by Django 3.1.5 on 2021-02-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0009_auto_20210216_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='papers', through='graphgenerator.AuthorPaper', to='graphgenerator.Author'),
        ),
        migrations.AlterField(
            model_name='authorpaper',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphgenerator.author'),
        ),
        migrations.AlterField(
            model_name='authorpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphgenerator.paper'),
        ),
    ]
