# Generated by Django 3.1.1 on 2021-01-10 16:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('graphgenerator', '0006_auto_20210110_1613'),
    ]

    operations = [
        TrigramExtension(),
    ]
