version: "3.9"

services: 

  elastic:
    container_name: icteridae-elastic
    image: elasticsearch:7.10.1
    environment: 
      - discovery.type=single-node
    volumes: 
      - elastic-data:/usr/share/elasticsearch/data/

  db:
    container_name: icteridae-postgres
    image: postgres
    environment: 
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes: 
      - db-data:/var/lib/postgresql/data/
    # Use for debugging database
    #ports:
    #  - "5433:5432"

  web:
    container_name: icteridae-django
    build: .
    command: "/bin/bash docker-entrypoint.sh"
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    depends_on: 
      - db
      - elastic

volumes: 
  db-data:
  elastic-data: