version: "3.9"

services: 

  elastic:
    image: elasticsearch:7.10.1
    environment: 
      - discovery.type=single-node

  db:
    image: postgres
    environment: 
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes: 
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  web:
    build: .
    command: "/bin/bash docker-entrypoint.sh"
    volumes: 
      - .:/code
      - ./data:/code/data
    ports: 
      - "8000:8000"
    depends_on: 
      - db
      - elastic

volumes: 
  db-data: